### PR TITLE
no longer checks for build receipt resource, skips Install and Download

### LINKED ISSUE #3: "could not determine wrapper version" after upgrading gradle
After upgrading gradle, any attempt to run groovyw quickly fails with this error:

```
Exception in thread "main" java.lang.RuntimeException: Could not determine wrapper version.
    at org.gradle.wrapper.GroovyWrapperMain.wrapperVersion(GroovyWrapperMain.java:111)
    at org.gradle.wrapper.GroovyWrapperMain.main(GroovyWrapperMain.java:63)
Caused by: java.lang.RuntimeException: No build receipt resource found.
    at org.gradle.wrapper.GroovyWrapperMain.wrapperVersion(GroovyWrapperMain.java:97)
    ... 1 more
```

The build receipt resource was removed in https://github.com/gradle/gradle/pull/7931

oh.

I thought the fix for this was going to be "change which resource it reads that version from."

But seeing that change to upstream, it looks like the fix is "delete this function entirely, because it was only used for some http header we're not too interested in keeping."

Further, if we're willing to place the burden on fetching and installing the gradle distribution on the project's gradle-wrapper, groovy-wrapper could leave out that `Install(Download())` bit entirely.

### PR DESCRIPTION
**Pull request by keturn**
This will no longer update the gradle distribution when gradle.properties changes. But it also invokes less code to possibly break with gradle changes.

Fixes #3.

and breaks #2 

That is, it no longer tries to put commons-io on the bootstrap classpath, because it's not in the current gradle distribution.

### CODE REVIEW

File: src/main/java/org/gradle/wrapper/GroovyWrapperMain.java [hunk 1]
```diff
@@ -55,13 +54,23 @@ public static void main(String[] args) throws Exception {
...
 
-        Logger logger = logger(options);
+        WrapperConfiguration config = WrapperExecutor.forWrapperPropertiesFile(propertiesFile).getConfiguration();
+        PathAssembler.LocalDistribution localDist = new PathAssembler(gradleUserHome).getDistribution(config);
+        File gradleHome = getAndVerifyDistributionRoot(localDist.getDistributionDir());
 
-        WrapperExecutor wrapperExecutor = WrapperExecutor.forWrapperPropertiesFile(propertiesFile);
-        wrapperExecutor.execute(
-                args,
-                new Install(logger, new Download(logger, "gradlew", wrapperVersion()), new PathAssembler(gradleUserHome)),
```
Comment (keturn) [inline src/main/java/org/gradle/wrapper/GroovyWrapperMain.java:63]: I axed all this `Install` and `Download` invocation, but if you want to _keep_ the download-and-install functionality, you leave this in and just replace that `wrapperVersion()` with org.gradle.wrapper.Download.UNKNOWN_VERSION: https://github.com/gradle/gradle/blob/00862b8160a09051e8226736314afd16e7f418f7/subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java#L24

aka `"0"`

File: src/main/java/org/gradle/wrapper/GroovyWrapperMain.java [hunk 2]
```diff
@@ -55,13 +54,23 @@ public static void main(String[] args) throws Exception {
...
-                new GroovyBootstrapMainStarter());
+        new GroovyBootstrapMainStarter().start(args, gradleHome);
+    }
+
+    static File getAndVerifyDistributionRoot(File distDir) {
+        // Extracted from org.gradle.wrapper.Install.getAndVerifyDistributionRoot
```
Comment (keturn) [inline src/main/java/org/gradle/wrapper/GroovyWrapperMain.java:65]: and then if you *keep* that `Install` invocation, there's no reason to have this duplicate copy of this method brought over from the Install class.

**Comment by Cervator** [comment]
Thanks @keturn :-)

Added back in that one piece, added details to the readme, did a version bump, and updated the target Gradle version for this repo as well via https://github.com/MovingBlocks/groovy-wrapper/commit/d51500f535ba343046cebcd82a33af23effc0c07
